apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snowman
resources:
  - database-migration.yaml
images:
  - name: ghcr.io/adikarthik/monolith-enterprise-application-migration
    newName: ghcr.io/adikarthik/monolith-enterprise-application-migration
    newTag: latest
