apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowman
  labels:
    app.kubernetes.io/name: snowman
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - snowman.example.com
      secretName: snowman-tls
  rules:
    - host: snowman.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snowman
                port:
                  name: http
