apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: snowman-ingress
  labels:
    app.kubernetes.io/name: snowman
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: snowman
      app.kubernetes.io/component: application
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8090
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8090
