apiVersion: v1
kind: ConfigMap
metadata:
  name: snowman-config
  labels:
    app.kubernetes.io/name: snowman
data:
  jdbc-driver: com.mysql.cj.jdbc.Driver
  jdbc-url: jdbc:mysql://mysql:3306/snowman?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  jms-broker-url: tcp://activemq:61616
  hibernate-ddl-auto: validate
